creating-components
lokkib/Music-Service pull request #1
Opened 2022-09-03 09:26 UTC by lokkib

2022-09-04 10:15 UTC, mrerberg commented
<img width="297" alt="Screenshot 2022-09-04 at 13 14 51" src="https://user-images.githubusercontent.com/103729911/188308473-53df6b0d-c3fa-4797-870c-40df83fece46.png">

У тебя 2 папки с картинками. Оставь одну

2022-09-04 10:19 UTC, mrerberg requested changes

2022-09-04 10:19 UTC, mrerberg commented on MusicServiceSample/css/style.css
> +* {
Тебе нет смысла вставлять весь css в один файл. В подобном файле есть смысл хранить глобальные стили, стили же компонентов должны лежать рядом с компонентами

2022-09-04 10:19 UTC, mrerberg commented on src/App.js
> +            <Footer />
Компонент футера пустой, можешь удалить

2022-09-04 10:19 UTC, mrerberg commented on src/components/Bar/Bar.js
> +function Bar() {
Рядом с файлом компонента должен лежать и файл стилей для компонента. Где они?

2022-09-04 10:19 UTC, mrerberg commented on src/components/Bar/Bar.js
> +function Bar() {
Предлагаю файл, где лежит компонент, именовать как index.jsx. Во-первых, так сократиться импорт. Во-вторых, мы используем правильное расширение (jsx), четко давая понять, что тут код компонента, а не чего-то другого

2022-09-04 10:19 UTC, mrerberg commented on src/components/Bar/bar-content/BarContent.js
> +import BarPlayerBlock from './bar-player-block/BarPlayerBlock';
У тебя идет смешение кейсов. И кебаб-кейс и кемелКейс. Выбери один

2022-09-04 10:19 UTC, mrerberg commented on src/components/Bar/bar-content/bar-player-block/bar-player-player/player-controls/PlayerControls.js
> +                    <use xlinkHref="img/icon/sprite.svg#icon-prev"></use>
Лучше делать не через спрайт, а создать каждую иконку как компонент

https://github.com/core-ds/icons/blob/master/packages/classic/src/AccountAddMBlackIcon.tsx

2022-09-04 10:19 UTC, mrerberg commented on src/components/Main/main-central-block/central-block-search/CentralBlockSearch.js
> +function CentralBlockSearch({ type = 'search', name = 'search' }) {
Приставка Center абсолютно лишняя

2022-09-05 06:26 UTC, mrerberg requested changes

2022-09-05 06:26 UTC, mrerberg commented on src/components/Bar/BarContent/BarPlayerBlock/BarPlayerPlayer/PlayerControls/PlayerControls.jsx
> +// import React, { SVGProps } from 'react';
Мертвый код следует удалить

2022-09-05 06:26 UTC, mrerberg commented on src/components/Main/MainCentralBlock/CentralBlockContent/PlaylistItem/PlaylistTrack/TrackTitle/TrackTitle.scss
> +    //&__title-text {}
Мертвый код

2022-09-05 06:26 UTC, mrerberg commented on src/components/Main/MainCentralBlock/MainCentralBlock.jsx
> +            <BlockSearch />
SearchBlock, SearchInput?

2022-09-06 06:33 UTC, mrerberg requested changes

2022-09-06 06:33 UTC, mrerberg commented on src/components/Bar/BarContent/BarPlayerBlock/BarPlayerPlayer/PlayerControls/PlayerControlsIcons/PlayerControlsPlay.jsx
> +function PlayerControlsPlay({ cls, alt }) {
Принято полно писать - className

2022-09-06 06:33 UTC, mrerberg commented on src/components/Bar/BarContent/BarPlayerBlock/BarVolumeBlock/BarVolume.scss
> +        // align-items: center;
Мертвый код

2022-09-06 09:21 UTC, lokkib commented on src/components/Bar/BarContent/BarPlayerBlock/BarVolumeBlock/BarVolume.scss
> +        // align-items: center;
+

2022-09-06 09:42 UTC, lokkib commented on src/components/Bar/BarContent/BarPlayerBlock/BarPlayerPlayer/PlayerControls/PlayerControlsIcons/PlayerControlsPlay.jsx
> +function PlayerControlsPlay({ cls, alt }) {
++

2022-09-07 06:28 UTC, mrerberg approved these changes

2022-09-07 06:28 UTC, mrerberg commented on src/components/Main/MainNav/NavMenu/MenuList/MenuItem.jsx
> +    classNameForLink = 'menu__link',
Это уже придирка, просто имей в виду. Когда у тебя пропс не просто className, то пишут как-то так

linkClassName
wrapperClassName

и т. п.

2022-09-07 15:44 UTC, merged