adding light-mode
lokkib/Music-Service pull request #9
Opened 2022-10-04 18:57 UTC by lokkib

2022-10-05 08:02 UTC, mrerberg requested changes

2022-10-05 08:02 UTC, mrerberg commented on src/pages/main/Tracks.jsx
> +    const [theme2, setTheme2] = useState(themes.dark);
А зачем столько стейтов?

2022-10-05 08:02 UTC, mrerberg commented on src/pages/main/Tracks.jsx
> +                <footer className="footer"></footer>
Фцтер не нужен

2022-10-05 08:02 UTC, mrerberg commented on src/pages/main/components/Main/MainNav/NavLogo/NavLogo.jsx
> +        elem = '../img/logo.png';
Это svg картинка? Svg картинку можно красить динамически через fill="currentColor"

2022-10-05 11:33 UTC, lokkib commented on src/pages/main/Tracks.jsx
> +    const [theme2, setTheme2] = useState(themes.dark);
Попытался исправить, установив только один стейт(themeMode), но почему-то режим не меняется, выслал новый коммит

2022-10-05 11:33 UTC, lokkib commented on src/pages/main/Tracks.jsx
> +                <footer className="footer"></footer>
+

2022-10-05 11:33 UTC, lokkib commented on src/pages/main/components/Main/MainNav/NavLogo/NavLogo.jsx
> +        elem = '../img/logo.png';
Сделал svg ++

2022-10-06 07:27 UTC, mrerberg commented
Зачем тебе 2 логотипа скайпро, если это свг? Ты ее можешь динамически красить

2022-10-06 07:27 UTC, mrerberg requested changes

2022-10-06 07:27 UTC, mrerberg commented on src/pages/main/components/Bar/Bar.jsx
> +        <StyledBar style={themeMode.dark}>
У тебя же здесь хардкод темной темы, зачем?

2022-10-06 07:27 UTC, mrerberg commented on src/pages/main/components/Bar/Bar.jsx
> +        <StyledBar style={themeMode.dark}>
Определи в теме ключ sideBar, к примеру, и в него клади нужны цвет в зависимости от темы

2022-10-06 09:10 UTC, lokkib commented on src/pages/main/components/Bar/Bar.jsx
> +        <StyledBar style={themeMode.dark}>
Не понимаю пока логику, можешь написать как пример применительно к компоненту Bar что надо сделать именно?

2022-10-07 08:48 UTC, mrerberg commented on src/pages/main/components/Bar/Bar.jsx
> +        <StyledBar style={themeMode.dark}>
У тебя сейчас в style залетает значение dark из themeMode. Почему? Тема же динамическая. Тебе надо определить в themeMode другой ключ совсем. Например

```
const themeMode = {
  bar: { ... }
}
```

2022-10-07 08:51 UTC, mrerberg commented on src/pages/main/components/Bar/Bar.jsx
> +        <StyledBar style={themeMode.dark}>
Суть в дом, что у тебя должно быть 2 объекта с одинаковыми ключами. Только значения ключей отличаются: одни для светлой темы, другие для темной

Вот грубый пример
```
const darkTheme = { heading: { color: 'white' } }

const lightTheme = { heading: { color: 'black' } }
```

И в зависимости от текущей выбранной темы, тебе в контекст нужно прокидывать то или иное значение (darkTheme/lightTheme)

2022-10-13 09:00 UTC, lokkib commented on src/pages/main/components/Bar/Bar.jsx
> +        <StyledBar style={themeMode.dark}>
const darkTheme = { heading: { color: 'white' } }

const lightTheme = { heading: { color: 'black' } }

Эти объекты где надо определить? Внутри компонента соответствующего или в темах(themes)? 

"Тебе надо определить в themeMode другой ключ совсем. Например
const themeMode = {
  bar: { ... }
}"

А как я могу заново определить themeMode, если он у меня уже определяется внутри компонента когда я useContext делаю?
function Bar() {
    const { themeMode } = useContext(ThemeContext);

2022-10-14 07:26 UTC, mrerberg commented on src/pages/main/components/Bar/Bar.jsx
> +        <StyledBar style={themeMode.dark}>
> Эти объекты где надо определить? Внутри компонента соответствующего или в темах(themes)?

Там где темы хранятся, там и определи

> А как я могу заново определить themeMode

Не понял вопроса. Суть в том, что оба объекта тем должны содержать одинаковые ключи. И коммент был к ключу dark. Как ключ dark может быть в светлой теме?

2022-10-14 07:29 UTC, mrerberg requested changes

2022-10-14 07:29 UTC, mrerberg commented on src/pages/playlists/playlistComponents/components/Main/MainNav/NavMenu/NavMenu.jsx
> +        theme2,
Господи, что это? У тебя из контекста должен прилетать объект с n-ым количеством ключей. Эти ключи могу стилизовать как раз любой компонент. Хранить значения для стилизации

2022-10-17 07:24 UTC, mrerberg requested changes

2022-10-17 07:24 UTC, mrerberg commented on src/pages/main/components/Bar/BarContent/BarPlayerBlock/BarPlayerPlayer/PlayerControls/PlayerControlsIcons/StyledPlayerControlIcons.js
> +export function PlayerControlIconNext({ alt }) {
А в чем смысл префиксов PlayerControl? Можно же просто назвать иконку абстрактно, мало ли где пригодиться ее использовать

2022-10-17 07:24 UTC, mrerberg commented on src/pages/main/components/Bar/BarContent/BarPlayerBlock/BarPlayerPlayer/PlayerControls/PlayerControlsIcons/StyledPlayerControlIcons.js
> +export function PlayerControlIconRepeat({ alt }) {
1 компонент - 1 файл

2022-10-17 07:24 UTC, mrerberg commented on src/pages/main/components/Bar/BarContent/BarPlayerBlock/BarPlayerPlayer/PlayerControls/PlayerControlsIcons/StyledPlayerControlIcons.js
>  const Svg5 = styled(Icon)`
Может все же более подходящее название придумаешь? Что за 5?

2022-10-17 07:24 UTC, mrerberg commented on src/pages/main/components/Main/MainCentralBlock/BlockSearch/StyledSearchInput.js
> +        color: ${(props) => (props.g === 'dark' ? 'white' : 'black')};
Что за пропс g?

2022-10-17 07:24 UTC, mrerberg commented on src/pages/main/components/Main/MainNav/NavLogo/StyledNavLogo.js
> +const Icon = styled.svg.attrs({
Эту переменную и ниже (Svg) можно заменить на атрибуты у тега svg. Зачем это отдельно выносить?

2022-10-17 07:24 UTC, mrerberg commented on src/pages/main/components/Main/MainNav/NavMenu/NavMenu.jsx
> +        element = './img/night-theme.png';
Ты можешь скачать данную картинку в svg формате и красить ее в зависимости от темы, а не подставлять другую картинку, так удобнее

2022-10-17 07:24 UTC, mrerberg commented on src/pages/playlists/playlistComponents/components/Bar/BarContent/BarPlayerBlock/BarPlayerPlayer/PlayerControls/PlayerControls.jsx
> +        if (icon) {
Ты ориентируешься на иконку в логике проигрывателя? Сомнительная идея

2022-10-17 07:24 UTC, mrerberg commented on src/pages/playlists/playlistComponents/components/Main/MainNav/NavMenu/NavMenu.jsx
> +import { useState } from 'react';
Реакт должен быть импортом в самом начале

2022-10-17 14:46 UTC, lokkib commented on src/pages/main/components/Bar/BarContent/BarPlayerBlock/BarPlayerPlayer/PlayerControls/PlayerControlsIcons/StyledPlayerControlIcons.js
> +export function PlayerControlIconNext({ alt }) {
++

2022-10-17 14:47 UTC, lokkib commented on src/pages/main/components/Bar/BarContent/BarPlayerBlock/BarPlayerPlayer/PlayerControls/PlayerControlsIcons/StyledPlayerControlIcons.js
> +export function PlayerControlIconRepeat({ alt }) {
Если в каждом файле должно быть по одному компоненту - для чего тогда существует импорт сразу нескольких компонентов как единого объекта? Как я в итоге и сделал: "import * as Styled from './PlayerControlsIcons/StyledPlayerControlIcons';"
Казалось, так можно

2022-10-17 14:47 UTC, lokkib commented on src/pages/main/components/Bar/BarContent/BarPlayerBlock/BarPlayerPlayer/PlayerControls/PlayerControlsIcons/StyledPlayerControlIcons.js
>  const Svg5 = styled(Icon)`
++

2022-10-17 14:48 UTC, lokkib commented on src/pages/main/components/Main/MainCentralBlock/BlockSearch/StyledSearchInput.js
> +        color: ${(props) => (props.g === 'dark' ? 'white' : 'black')};
++

2022-10-17 14:53 UTC, lokkib commented on src/pages/main/components/Main/MainNav/NavLogo/StyledNavLogo.js
> +const Icon = styled.svg.attrs({
Если правильно понял что делать, я это сделал применительно к этому компоненту (IconPrev), но именно потому, что тут всего несколько атрибутов, которые надо было вставить - xmlns, width, height.   Но что делать с рядом других svg компонентов, где есть также стили с hover и тд.

 export function IconPrev({ alt }) {
    const { themeMode } = useContext(ThemeContext);

    return (
        <svg
            xmlns="http://www.w3.org/2000/svg"
            width="15px"
            height="14px"
            alt={alt}
            fill="none"
            viewBox="0 0 16 14"
        >
            <path
                style={themeMode.trackIconsStroke}
                d="M1 2V12.5"
                stroke="white"
            />
            <path
                style={themeMode.trackIconsFill}
                d="M3 7L12.75 0.937823L12.75 13.0622L3 7Z"
                fill="#D9D9D9"
            />
        </svg>
    );
}


Как пример: 
const SvgPlayStop = styled(Icon)`
    width: 22px;
    height: 20px;
    fill: #d9d9d9;
    &:active {
        fill: transparent;
        stroke: #ffffff;
        cursor: pointer;
    }
    &:hover {
        fill: transparent;
        stroke: #acacac;
        cursor: pointer;
    }
`;

2022-10-17 14:54 UTC, lokkib commented on src/pages/main/components/Main/MainNav/NavMenu/NavMenu.jsx
> +        element = './img/night-theme.png';
Но это разные картинки - полумесяц в темной теме и солнце в светлой - то есть сделать два разных компонента и подставлять их? Просто непонятно как можно одним покрашиванием обойтись

2022-10-17 14:55 UTC, lokkib commented on src/pages/playlists/playlistComponents/components/Bar/BarContent/BarPlayerBlock/BarPlayerPlayer/PlayerControls/PlayerControls.jsx
> +        if (icon) {
++

2022-10-17 14:56 UTC, lokkib commented on src/pages/playlists/playlistComponents/components/Main/MainNav/NavMenu/NavMenu.jsx
> +import { useState } from 'react';
Речь про импорт Реакта в каждом файле именно (читал, что вроде это необязательно стало с какой-то версии Реакта) или про хуки из Реакта?

2022-10-18 06:12 UTC, mrerberg commented on src/pages/playlists/playlistComponents/components/Main/MainNav/NavMenu/NavMenu.jsx
> +import { useState } from 'react';
Про любой импорт из реакта. Так наглядно, что это именно компонент)

2022-10-18 06:13 UTC, mrerberg commented on src/pages/main/components/Main/MainNav/NavMenu/NavMenu.jsx
> +        element = './img/night-theme.png';
Точно, протупил. Ты прав. Но все равно их можно svg-шками вставить, удобнее будет

2022-10-18 06:15 UTC, mrerberg commented on src/pages/main/components/Bar/BarContent/BarPlayerBlock/BarPlayerPlayer/PlayerControls/PlayerControlsIcons/StyledPlayerControlIcons.js
> +export function PlayerControlIconRepeat({ alt }) {
Можно, как хочется, но распространенной практикой является хранение в 1 файле 1 компонента, так управлять проще. Понятна структура, ясно, что тебе ожидать, когда заглядываешь в файл

2022-10-18 06:19 UTC, mrerberg requested changes

2022-10-18 06:19 UTC, mrerberg commented on src/pages/playlists/playlistComponents/components/Bar/BarContent/BarPlayerBlock/BarPlayerPlayer/PlayerControls/PlayerControlsIcons/StyledPlayerControlIcons.js
> +const SvgRepeat = styled(Icon)`
Ты же можешь передать либо класс, либо обернуть IconRepeat по месту использования, чтобы задать стили, подобные cursor: pointer;

2022-10-18 06:19 UTC, mrerberg commented on src/pages/playlists/playlistComponents/components/Bar/BarContent/BarPlayerBlock/BarPlayerPlayer/PlayerControls/PlayerControlsIcons/StyledPlayerControlIcons.js
> +const SvgRepeat = styled(Icon)`
Потому как этот стиль частный случай использования иконки, мне так кажется.

2022-10-18 14:02 UTC, lokkib commented on src/pages/playlists/playlistComponents/components/Main/MainNav/NavMenu/NavMenu.jsx
> +import { useState } from 'react';
++

2022-10-18 14:02 UTC, lokkib commented on src/pages/main/components/Main/MainNav/NavMenu/NavMenu.jsx
> +        element = './img/night-theme.png';
++

2022-10-18 14:02 UTC, lokkib commented on src/pages/main/components/Main/MainNav/NavLogo/StyledNavLogo.js
> +const Icon = styled.svg.attrs({
++

2022-10-18 14:03 UTC, lokkib commented on src/pages/main/components/Bar/BarContent/BarPlayerBlock/BarPlayerPlayer/PlayerControls/PlayerControlsIcons/StyledPlayerControlIcons.js
> +export function PlayerControlIconRepeat({ alt }) {
++

2022-10-18 14:05 UTC, lokkib commented on src/pages/playlists/playlistComponents/components/Bar/BarContent/BarPlayerBlock/BarPlayerPlayer/PlayerControls/PlayerControlsIcons/StyledPlayerControlIcons.js
> +const SvgRepeat = styled(Icon)`
Исправил как я это понял

2022-10-19 06:18 UTC, mrerberg requested changes

2022-10-19 06:18 UTC, mrerberg commented on src/pages/main/components/Bar/BarContent/BarPlayerBlock/BarPlayerPlayer/PlayerControls/PlayerControls.jsx
> +        <PlayerControlsContainer style={{ alignItems: 'center' }}>
Не инлайн стили, задай через StyledComponent

2022-10-19 06:18 UTC, mrerberg commented on src/pages/main/components/Bar/BarContent/BarPlayerBlock/BarPlayerPlayer/PlayerControls/PlayerControlsIcons/IconNext.jsx
> +const SvgNext = styled.svg.attrs({
Атрибуты задай через html, непосредственно SvgNext как alt. Не нужно это через SC делать

2022-10-19 06:18 UTC, mrerberg commented on src/pages/main/components/Bar/BarContent/BarPlayerBlock/BarPlayerPlayer/PlayerControls/StyledPlayerControls.js
> +// import styled from 'styled-components';
?

2022-10-19 06:18 UTC, mrerberg commented on src/pages/playlists/playlistComponents/components/Bar/BarContent/BarPlayerBlock/BarPlayerPlayer/PlayerTrackPlay/TrackPlayLikeDislike/TrackPlayLikeDislike.jsx
> +import { PlayIconDislike } from '../../../../../../../../../main/components/Bar/BarContent/BarPlayerBlock/BarPlayerPlayer/PlayerTrackPlay/TrackPlayLikeDislike/TrackPlayLikeDislikeIcons/StyledPlayIcon
Тебя самого не смущает подобная вложенность? Это жутко выглядит. Тебе нужно подумать, как можно реорганизовать структуру компонентов

2022-10-19 06:18 UTC, mrerberg commented on src/pages/playlists/playlistComponents/components/Bar/BarContent/BarPlayerBlock/BarPlayerPlayer/PlayerTrackPlay/TrackPlayLikeDislike/TrackPlayLikeDislike.jsx
> +import { PlayIconDislike } from '../../../../../../../../../main/components/Bar/BarContent/BarPlayerBlock/BarPlayerPlayer/PlayerTrackPlay/TrackPlayLikeDislike/TrackPlayLikeDislikeIcons/StyledPlayIcon
Во-первых, файл с компонентом можно называть index.jsx, тогда путь на 1 ячейку будет короче
Во-вторых, есть смысл перейти к плоской структуре, а не вложенной

2022-10-20 08:29 UTC, lokkib commented on src/pages/main/components/Bar/BarContent/BarPlayerBlock/BarPlayerPlayer/PlayerControls/PlayerControlsIcons/IconNext.jsx
> +const SvgNext = styled.svg.attrs({
++

2022-10-20 08:29 UTC, lokkib commented on src/pages/main/components/Bar/BarContent/BarPlayerBlock/BarPlayerPlayer/PlayerControls/StyledPlayerControls.js
> +// import styled from 'styled-components';
++

2022-10-20 08:29 UTC, lokkib commented on src/pages/main/components/Bar/BarContent/BarPlayerBlock/BarPlayerPlayer/PlayerControls/PlayerControls.jsx
> +        <PlayerControlsContainer style={{ alignItems: 'center' }}>
++

2022-10-20 09:21 UTC, lokkib commented on src/pages/main/components/Bar/BarContent/BarPlayerBlock/BarPlayerPlayer/PlayerControls/PlayerControlsIcons/IconNext.jsx
> +const SvgNext = styled.svg.attrs({
Можешь пожалуйста прояснить для меня как это сделать и для чего? Пока не понимаю что сделать со стилями, куда их поместить, если не использовать SC. Скрины прикладываю как было и что пытаюсь сделать
![Снимок экрана1](https://user-images.githubusercontent.com/101714147/196909528-907c4bae-f6f8-460c-a0e7-789922acb7be.png)
![Снимок экрана2](https://user-images.githubusercontent.com/101714147/196909563-7f3c356a-83e7-4e89-b993-f14e91e92cb0.png)

2022-10-21 07:09 UTC, mrerberg commented on src/pages/main/components/Bar/BarContent/BarPlayerBlock/BarPlayerPlayer/PlayerControls/PlayerControlsIcons/IconNext.jsx
> +const SvgNext = styled.svg.attrs({
import { useContext } from 'react';
import styled from 'styled-components';

import ThemeContext from '../../../../../../../../../themes';

const Svg = styled.svg`
    &:active {
        fill: transparent;
        stroke: #ffffff;
        cursor: pointer;
    }
    &:hover {
        fill: transparent;
        stroke: #acacac;
        cursor: pointer;
    }
`;

export function IconNext({ alt }) {
    const { themeMode } = useContext(ThemeContext);

    return (
        <SvgNext alt={alt}  xmlns='http://www.w3.org/2000/svg'   width="15px" height="14px" ...>
            <path
                style={themeMode.trackIconsStroke}
                d="M15 2V12.5"
                stroke="white"
            />
            <path
                style={themeMode.trackIconsFill}
                d="M13 7L3.25 0.937823L3.25 13.0622L13 7Z"
                fill="#D9D9D9"
            />
        </SvgNext>
    );
}

2022-10-22 12:39 UTC, mrerberg approved these changes

2022-10-25 12:54 UTC, merged